version: '3'
services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb-userservice
    ports:
      - ${DB_OUT_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    env_file: ./.env
    # volumes:
    #   - mysqldb:/var/lib/mysql 
  userservice:
    container_name: myserver
    environment:
      DB_HOST: mysqldb
    depends_on:
      - mysqldb
    build:
      context: ./server
    ports:
      - 8080:8080
      - 50051:50051
  envoy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: hello_lupin
    container_name: Greeter-userserivce
    ports:
      - 7000:7000
      - 7001:7001